name: Install MongoDB via Supercharge

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:  
  install-mongodb:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout repository  
        uses: actions/checkout@v4  
  
      - name: Install MongoDB 8.0 Community  
        uses: supercharge/mongodb-github-action@1.10.0  
        with:  
          mongodb-version: '8.0'  
  
      - name: Install mongocryptd from Enterprise tarball  
        run: |  
          curl -o mongodb-enterprise.tar.gz https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-enterprise-ubuntu2004-8.0.0.tgz  
          tar -xzf mongodb-enterprise.tar.gz  
          sudo cp mongodb-linux-x86_64-enterprise-ubuntu2004-8.0.0/bin/mongocryptd /usr/local/bin/  
  
      - name: Start mongocryptd  
        run: |  
          nohup mongocryptd --logpath=/tmp/mongocryptd.log &  
  
      - name: Verify MongoDB installation  
        run: |  
          mongosh --version  
          mongosh --eval 'db.runCommand({ connectionStatus: 1 })'  
  
      - name: Verify mongocryptd is running  
        run: |  
          pgrep mongocryptd  
          ps aux | grep mongocryptd  

