name: Install MongoDB via Supercharge

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install-mongodb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install MongoDB with supercharge/mongodb-github-action
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: '6.0'
      - name: Verify MongoDB installation
        run: |
          mongo --version
          mongo --eval 'db.runCommand({ connectionStatus: 1 })'
